apiVersion: "v1"
kind: Pod
metadata:
  name: mysql
  labels:
    name: mysql
    app: java
spec:
  containers:
    - name: mysql
      image: navyateja/mysqlp
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: Welcome@1234
      ports:
        - containerPort: 3306
          protocol: TCP

