apiVersion: v1
kind: Service
metadata:
  name: javaweb
  labels:
    name: javaweb
    app: java
spec:
  selector:
    name: javaweb
  type: NodePort
  ports:
   - port: 8080
     targetPort: 8080 
     protocol: TCP
     nodePort: 30095

